#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 27 11:57:58 2022

@author: hayley
"""

"""
Randomly set the condition order that participants will be assigned to.
There will be 120 participants and 4 possible orders (control-control, control-strategy, strategy-control, strategy-strategy).
"""


# import modules
import random, numpy as np



# set up variables
n=120 # number of participants
cond = 0,1,2,3 #conditions
nCond = n/len(cond) # number of subs per condition, 

orderList = np.repeat(cond, nCond); 
random.shuffle(orderList)