# This is a configuration file for the config package written
# by RStudio. To use, make sure the package `config` is installed,
# via console:
#
# R > install.packages("config")
#
# Then, you can load within a notebook chunk with `library(config)`.
#
# To use default config settings, simply write `config::get()`.
#
# You can learn more at:
#   https://cran.r-project.org/web/packages/config/vignettes/introduction.html.
default:
  path:
    data: 
      Rdata: "/Volumes/shlab/Projects/RCS/data/Rdata"
      symspData: "/Volumes/shlab/Projects/RCS/data/symspanData"
      ospData: "/Volumes/shlab/Projects/RCS/data/ospanData"
      rdmData: "/Volumes/shlab/Projects/RCS/data/rdmData"
    directory: "/Volumes/shlab/Projects/RCS"
    code_files:
      choiceSetFx: "../choiceSet/rcsChoiceSet.R"
      dataQA: "../analysis/rcsDataQA.Rmd"
      dataSetUp: "../analysis/rcsDataSetup.R"
      basicAnalysis: "../analysis/rcsBasicAnalysis.Rmd"
    shlab_figures: "figures"
    task_files: "../task"


