---
title: "rcs_runStan"
author: "Hayley Brooks"
date: "2023-01-17"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())

library('config')
config = config::get()

# load packages
library(rstan)
library(parallel)

# load data file
#load(file.path(config$path$data$Rdata, "rdmDFall_clean.Rdata"))
setup_source = "/Users/shlab/Documents/GitHub/rcs/analysis/rcsDataSetup.R" # run our set up script (which loads all the data)
#setup_source = "/Users/hayley/Documents/GitHub/rcs/analysis/rcsDataSetup.R"
source(setup_source) #, local = knitr::knit_global())

```

```{r data-setup}

# Data needs to be in a list, e.g stanData = list(subID = rdmDFall_clean$subID, etc)
#   USE EXACT SAME VARIABLE NAMES FROM STAN FILE
#    data cannot have any nans, replace with zeroes

# because we excluded people, the subIDs skip numbers and stan can't handle this so we need to change the subIDs to be linearly
subIDs = as.numeric(unique(rdmDFclean$subID))
nSub= length(subIDs)

rdmDFclean$subIDnumeric = as.numeric(rdmDFclean$subID)

for (s in 1:nSub){
  rdmDFclean$subIDnumeric[as.numeric(rdmDFclean$subID)==subIDs[s]] = s
}

rcsDataList = list(
  choices = rdmDFclean$choice,
  gain = rdmDFclean$riskyGain,
  safe = rdmDFclean$safe,
  poc = rdmDFclean$pocStanScaled,
  ind = as.numeric(rdmDFclean$subIDnumeric),
  nsubj = nSub,
  N = length(rdmDFclean$choice)
)


```


```{r call-stan-program}
#stanModel = "/Users/shlab/Documents/GitHub/rcs/analysis/stan/rcs_basic0_rhomu.stan"
#stanModel = "/Users/hayley/Documents/GitHub/rcs/analysis/stan/rcs_basic0_rhomu.stan"
#stanModel = "/Users/shlab/Documents/GitHub/rcs/analysis/stan/rcs_basic0_rhomudb.stan"
stanModel = "/Users/shlab/Documents/Github/rcs/analysis/stan/rcs_rhomudb_pocadj.stan"
#stanModel = "/Users/hayley/Documents/Github/rcs/analysis/stan/rcs_rhomudb_pocadj.stan"
```

```{r configure-the-model}

# define some things
nChains = 4 # number of chains (1 chain per core)
fitSteps = 10000 # stan will save half of this many x nChains per parameter (for bigger samples, do 10,000 - for testing do 200)

pars = c('meanRho', 'meanMu', 'meanDB',
         'sdRho', 'sdMu', 'sdDB',
         'r', 'm', 'db',
         'meanPocAdjDB','sdPocAdjDB','pocAdjDB',
         'meanPocAdjR','sdPocAdjR','pocAdjR',
         'meanPocAdjM','sdPocAdjM','pocAdjM');


starttime = proc.time()[3];

seed = runif(1,1,1e6); # stan needs random integer from 1 to max supportable

# compile the model
fit0 = stan(file = stanModel, data =rcsDataList, iter = 1, chains = 1, pars=pars, init_r = 1); # this initializes or sets up the model

fit0time = proc.time()[3];
print(noquote(sprintf('Compilation time = %.1f seconds',(fit0time-starttime))));

# fit with paralellization
seed <- runif(1,1,1e6); # Stan wants a random integer from 1 to max supportable

sflist1 <-
  mclapply(1:nChains, mc.cores = nChains,
           function(i) stan(fit = fit0, seed=seed, data = rcsDataList,
                            iter = fitSteps, chains = 1, chain_id = i,
                            pars = pars, init_r = 1))

fittime = proc.time()[3];
print(noquote(sprintf('Sampling time = %.1f minutes.',(fittime-fit0time)/60)))



sflistFinal = list();
k = 1;
for (i in 1:nChains){
  if (any(dim(sflist1[[i]]) > 0)) {
    sflistFinal[[k]] <- sflist1[[i]]
    k = k + 1;
  }
  else {print(noquote(sprintf('WARNING: Chain %d did not include any samples.',i)))}
}

save(stanModel,sflistFinal, file = sprintf('/Volumes/shlab/Projects/RCS/data/Rdata/stanModelOutput/rcs_rhoMuDB_pocadj_%s.Rdata',format(Sys.Date(), format="%Y%m%d")))

```




```{r resources}
# https://ourcodingclub.github.io/tutorials/stan-intro/

# https://www.r-bloggers.com/2019/01/an-introduction-to-stan-with-r/

# https://github.com/sokolhessnerlab/cbm_Brooks2020
```

