---
title: "rcs_basicStanAssess"
author: "Hayley Brooks"
date: "2023-02-03"
output: html_document
---

Load and assess model fit for stan models for HRB's dissertation (RCS)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(config)
library(rstan)
config = config::get()


load(file.path(config$path$data$Rdata, 'stanModelOutput/rcs_basicRhoMu_20230125.Rdata'));

```


```{r}

fit1 <- sflist2stanfit(sflistFinal)

sSamples <- extract(fit1)
q95 <- c(0.025,0.975);q90 <- c(0.05,0.95);q85 <- c(0.075,0.925);q80 <- c(0.1,0.9);q75 <- c(0.125,0.875);q70 <- c(0.15,0.85)
 
print(fit1)

fit1summ = summary(fit1);

neffs = fit1summ$summary[,'n_eff'];
rhats = fit1summ$summary[,'Rhat'];


meanparams = c('meanRho','meanMu')

sdparams = c('sdRho','sdMu')

neffs[meanparams]
rhats[meanparams]

neffs[sdparams]
rhats[sdparams]


# Means and 95% CIs for main parameters
exp(mean(sSamples$meanRho))
exp(quantile(probs=q95,sSamples$meanRho))


exp(mean(sSamples$meanMu))
exp(quantile(probs=q95,sSamples$meanMu))


# 2/3/23: model results look reasonable and the rhats are ~1 which is good, will run this model again with many more samples. 

```

