---
title: "rcs_runStan"
author: "Hayley Brooks"
date: "2023-01-17"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())

library('config')
config = config::get()

# load packages
library(rstan)


# load data file
load(file.path(config$path$data$Rdata, "rdmDFall_clean.Rdata"))

```

```{r data-setup}

# Data needs to be in a list, e.g stanData = list(subID = rdmDFall_clean$subID, etc)
#   USE EXACT SAME VARIABLE NAMES FROM STAN FILE
#    data cannot have any nans, replace with zeroes

rdmDFclean$subIDnumeric = as.numeric(rdmDFclean$subID)

# rcsDataList = list(
#   choices = rdmDFclean$choice,
#   gain = rdmDFclean$riskyGain,
#   safe = rdmDFclean$safe,
#   ind = as.numeric(rdmDFclean$subIDnumeric),
#   nsubj = length(unique(rdmDFclean$subID)),
#   N = length(rdmDFclean$choice)
# )

rcsDataList = list(
  choices = rdmDFclean$choice,
  gam1 = rdmDFclean$riskyGain,
  cert = rdmDFclean$safe,
  ind = as.numeric(rdmDFclean$subIDnumeric),
  nsubj = length(unique(rdmDFclean$subID)),
  N = length(rdmDFclean$choice)
)


```


```{r call-stan-program}
#stanModel = "/Users/shlab/Documents/GitHub/rcs/analysis/rcs_practiceStan.stan"
stanModel = "/Users/shlab/Documents/GitHub/rcs/analysis/rcs_stanCBMcopy.stan"

```

```{r fit-the-model}

# define some things
nChains = 6 # number of chains (1 chain per core)
fitSteps = 2000 # stan will save half of this many x nChains per parameter

pars = c('meanRho', 'meanMu',
         'sdRho', 'sdMu',
         'r', 'm');

starttime = proc.time()[3];

seed = runif(1,1,1e6); # stan needs random integer from 1 to max supportable
# compile the model
fit0 = stan(file = stanModel, data =rcsDataList, iter = 1, chains = 1, pars=pars); # this initializes or sets up the model

fit0time = proc.time()[3];
print(noquote(sprintf('Complication time = %.1f seconds',(fit0time-starttime))));

```


```{r assess-model-fit}

```




```{r resources}
# https://ourcodingclub.github.io/tutorials/stan-intro/

# https://www.r-bloggers.com/2019/01/an-introduction-to-stan-with-r/

# https://github.com/sokolhessnerlab/cbm_Brooks2020
```

