---
title: "RCS Basic Analysis"
author: "Hayley Brooks"
date: "2022-10-12"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())

library('config')
config = config::get()


setup_source = file.path(config$path$code_files$dataSetUp) # run our set up script (which loads all the data)
source(setup_source) #, local = knitr::knit_global())
```


```{r, score-ospan}
#OSPAN Absolute Score: The sum of the correctly recalled elements from only the items in which all the elements are recalled in correct serial order (formally OSPAN Score)

# participants had to keep percent correct math at 85% or above
if (any(ospanDF$percentCorrectMath[ospanDF$...1==25]<85)){
  ospanExclude = ospanDF$subID[ospanDF$...1 ==25 & ospanDF$percentCorrectMath <85]
  ospanDF = ospanDF[which(!ospanDF$subID %in% ospanExclude),] # apply exclusion
}

# subID char won't work when we remove participants for <85 correct math
# score and add to ospanDF
# for (s in 1:nSub) {
#   ospanDF$absScore[ospanDF$subID==subIDchar[s]] = sum(ospanDF$correctCount[ospanDF$correctCount==ospanDF$setSize & ospanDF$subID==subIDchar[s]], na.rm = T)
# 
# }


```

```{r, score-symspan}
#SSPAN Absolute Score: The sum of the correctly recalled elements from only the items in which all the elements are recalled in correct serial order (formally SSPAN Score)

# participants had to keep percent correct symmetry at 85% or above
if (any(symspanDF$percentCorrectSym[symspanDF$...1==14]<85)){
  symspanExclude = symspanDF$subID[symspanDF$...1 ==14 & symspanDF$percentCorrectSym <85]
  symspanDF = symspanDF[which(!symspanDF$subID %in% symspanExclude),] # apply exclusion
}

# subID char won't work when we remove participants for <85 correct symmetry
# score and add to symspanDF
# for (s in 1:nSub) {
#   symspanDF$absScore[symspanDF$subID==subIDchar[s]] = sum(symspanDF$squareCorrectCount[symspanDF$squareCorrectCount==symspanDF$setSize & symspanDF$subID==subIDchar[s]], na.rm = T)
# 
# }

```


```{r, rdm}
pgam = mean(rdmDFclean$choice, na.rm=T) # overall, across rounds
pgamRound1 =mean(rdmDFclean$choice[rdmDFclean$roundRDM==1], na.rm=T) # overall, round 1
pgamRound2 =mean(rdmDFclean$choice[rdmDFclean$roundRDM==2], na.rm=T) # overall, round 2

# differences in pgam from round 1 to round 2:
pgamDiff = RDMqualityCheck$pgambleRound1[!RDMqualityCheck$subID %in% as.numeric(excludeSubID)] - RDMqualityCheck$pgambleRound2[!RDMqualityCheck$subID %in% as.numeric(excludeSubID)]


# pgam in condition (quick estimate - don't make too much of this - doesn't take into account ordder of condition)

mean(rdmDFclean$choice[rdmDFclean$strategy==0 & rdmDFclean$roundRDM==1], na.rm=TRUE)
mean(rdmDFclean$choice[rdmDFclean$strategy==0 & rdmDFclean$roundRDM==2], na.rm=TRUE)

mean(rdmDFclean$choice[rdmDFclean$strategy==1 & rdmDFclean$roundRDM==1], na.rm=TRUE)
mean(rdmDFclean$choice[rdmDFclean$strategy==1 & rdmDFclean$roundRDM==2], na.rm=TRUE)




```

```{r trial-level-glmer}

model1_trialLev= glmer(choice ~ 1 + gainScaled + safeScaled + evLevScaled + (1|subID), data=rdmDFclean , family = "binomial")

summary(model1_trialLev)

# get residuals

```

```{r save-predicted-values}
rdmDFclean$pred= predict(model1_trialLev,type="link"); 
par(mfrow=c(1,1))
#plot(mriBehClean$pred, ylab="predicted values");

```



```{r basic-recent-events-model}

model2_3timescales = glmer(choice ~ 0 + pastOC1sc + posShift + earningsSC + trialSC+ (1|subIDnum), data=rdmDFclean[rdmDFclean$strategy==1,], family="binomial", offset=pred)

```

```{r plot-basics}

pdf("/Users/hayley/Desktop/shenhavLabTalk/risk-taking_rounds.pdf")
plot(RDMqualityCheck$pgambleRound1[-c(12,15)]-RDMqualityCheck$pgambleRound2[-c(12,15)], ylab ="pGamble(round 1 - round 2)", xlab="participant", main="change in risk-taking across rounds", axes=F, pch=16, col="maroon", cex=1.5, ylim=c(-.4,.4), xlim=c(1,24))
abline(h=0, col="grey", lty="dashed")
axis(1, at = 1:nSub, labels = 1:nSub, lwd=3)
axis(2, at = seq(-.4, .4, .1), lwd=3)
dev.off()


# create a variable for condition code
# 1 = control, control
# 2 = control, strategy
# 3 = strategy, control
# 4 = strategy, strategy

pdf("/Users/hayley/Desktop/shenhavLabTalk/rpgamByRoundAllcond.pdf")
par(pty="s")
plot(RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode1)], RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode1)], asp=1,col="blue", pch=16, ylim=c(0,1), xlim=c(0,1), ylab="p(gamble round 1)", xlab="p(gamble round 2)", axes=F, cex=4)

abline(a = 0, b=1, lty="dashed", col="darkgrey",lwd=5)

points(RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode2)], RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode2)], col="green",asp=1, pch=16,cex=4)

points(RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode3)], RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode3)], asp=1, col="red", pch=16, cex=4)


points(RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode4)], RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode4)], asp= 1,col="purple", pch=16, cex=4)
axis(1, lwd=6)
axis(2, lwd=6)
dev.off()


pdf("/Users/hayley/Desktop/shenhavLabTalk/rpgamDiff_cond2_cond3.pdf")
plot(c(RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode2)]- RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode2)], RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode3)]- RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode3)]), pch=16, ylab="Risk-taking\n (round 1 - round 2)", xlab="participant", ylim=c(-.5,.5),cex= 4,col=c(rep("green",length(condcode2)), rep("red", length(condcode3))), axes=F)
axis(1, at = 1:13, labels = as.numeric(c(condcode2, condcode3)), lwd=6, cex.axis=1)
axis(2, lwd=6, cex=1.5)
abline(h=0, col="darkgrey", lty="dashed", lwd=4)

points(c(RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode2)]- RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode2)], RDMqualityCheck$pgambleRound1[RDMqualityCheck$subID %in% as.numeric(condcode3)]- RDMqualityCheck$pgambleRound2[RDMqualityCheck$subID %in% as.numeric(condcode3)]), pch=16, cex= 4,col=c(rep("green",length(condcode2)), rep("red", length(condcode3))))
dev.off()



```

