---
title: "Models for Brooks & Sokol-Hessner (2023)"
author: "Hayley Brooks"
date: "2023-03-12"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
### This R markdown file includes all models of results reported in the main text and supplememntal analyses of 'Cognitive strategy use selectively changes temporal context effects in risky monetary decision-making' (Brooks & Sokol-Hessner, 2023)

```{r setup, include=FALSE}
rm(list=ls())

library('config')
config = config::get()

library('lmerTest')
library(dplyr)

setup_source = file.path(config$path$code_files$dataSetUp) # run our set up script (which loads all the data)
source(setup_source) #, local = knitr::knit_global())


sem <- function(x) sd(x)/sqrt(length(x)); # set up sem function for later analyses

```


Main text results:
```{r subjective-experiences-cognitive-processing-across-conditions}
# Do difficulty ratings, frequency and reaction time vary across conditions?
rcsSubLevelLong_clean$strategyRecode = rcsSubLevelLong_clean$strategy
rcsSubLevelLong_clean$strategyRecode[rcsSubLevelLong_clean$strategyRecode==0]= -1
rcsSubLevelLong_clean$rdmRound = rep(c(-1,1), times = nSub)

mean(rcsSubLevelLong_clean$instDifficult[rcsSubLevelLong_clean$strategy==0])
mean(rcsSubLevelLong_clean$instDifficult[rcsSubLevelLong_clean$strategy==1])

difficultyRoundStrat = lmer(instDifficult~strategyRecode*rdmRound + (1|subID), data=rcsSubLevelLong_clean); # no effect of round or strategy, no interaction on difficulty ratings in linear mixed effects model
summary(difficultyRoundStrat)


mean(rcsSubLevelLong_clean$instHowOften[rcsSubLevelLong_clean$strategy==0])
mean(rcsSubLevelLong_clean$instHowOften[rcsSubLevelLong_clean$strategy==1])

frequencyRoundStrat = lmer(instHowOften~strategyRecode*rdmRound + (1|subID), data=rcsSubLevelLong_clean); # no effect of round or strategy, no interaction on difficulty ratings in linear mixed effects model
summary(frequencyRoundStrat); # no effect of strategy on frequency, potential effect of round (trending at p=.08), no interaction where frequency is lower in round 2 consistent with results above


RT_roundStrat_500ms= lmer(sqrt(RT) ~ roundRDM + strategyRecode + roundRDM*strategyRecode + (1|subID), data= rdmDFclean[rdmDFclean$RT>.5,]);
summary(RT_roundStrat_500ms); 

# round 1, nat: -.04*-1 + -.014*-1 +  .01*-1*-1 = .064 weight on RT
# round 1, strat: -.04*-1 + -.014*1 +  .01*-1*1 = .016 weight on RT
# round 2, nat: -.04*1 + -.014*-1 +  .01*-1*1 = -.036 weight on RT
# round 2, strat: -.04*1 + -.014*1 +  .01*1*1 = -.044 weight on RT

# calculate the implied mean RT based on above model:
# start with overall mean sqrt RT = 1.15s (median =1.11s)
# round 1, nat: 1.15 +.064 = 1.214s
# round 1, strat: 1.15 +.016  = 1.166s
# round 2, nat: 1.15 -.036 = 1.114s
# round 2, strat: 1.15 -.044 = 1.106s

```

```{r Perceived-independence-of-gambling-task-rounds}
# Do participants perceive rounds of gambling task as independent?
rcsSubLevelWide_clean$rdmRoundsIndepNumeric = as.numeric(rcsSubLevelWide_clean$rdmRoundsIndep)
summary(rcsSubLevelWide_clean$rdmRoundsIndepNumeric); # mean= 4.99; median = 5; range = 1-7 (on a scale from 1-7)
sd(rcsSubLevelWide_clean$rdmRoundsIndepNumeric); # 1.553888

# Does round independence depend on participants' experiences with strategy and order? (ANOVA)
roundIndepAnova = aov(rdmRoundsIndepNumeric~factor(condCode), data = rcsSubLevelWide_clean)
summary(roundIndepAnova); # check results: 
plot(roundIndepAnova); # plots anova diagnostics to check for homoscedasticity


```

```{r strategic-effect-on-context-depends-on-reappraisal, echo=TRUE}

# Account for current trial-level variables, strategy, and round:
trialLevelModel = glmer(choice ~ 1 + gainScaled + safeScaled + evLevScaled + roundRecode*strategyRecode + (1|subID), data=rdmDFclean , family = "binomial")
summary(trialLevelModel)

# Save predicted values for contextual models:
rdmDFclean$predTrialLevModel= predict(trialLevelModel,type="link"); 

# Is strategic effect related to each of the 4 covariates?
model1 = glm(choice~0 + pastOC1sc*strategyRecode + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode + suppSpan0mean*strategyRecode + reapSpan0mean*strategyRecode + motivationNumeric*strategyRecode + compositeSpanScore*strategyRecode, data=rdmDFclean, family="binomial",offset=predTrialLevModel);
summary(model1);

# Reappraisal appears to be the only covariate that is related to strategy-use in this dataset.
# Does the effect of strategy on temporal context in risk co-vary with ERQ reappraisal?
model2 = glm(choice~0 + pastOC1sc*strategyRecode*reapSpan0mean + signedShiftsc*strategyRecode*reapSpan0mean + earnNormalizedOverall*strategyRecode*reapSpan0mean + linExpectation*strategyRecode*reapSpan0mean, data=rdmDFclean, family="binomial",offset=predTrialLevModel);
summary(model2);


# Exploratory analysis: splitting up reappraisal into tertiles to understand potential nonlinearities between low, medium and high reappraisal groups.
model3 = pocShiftEarnExp_ERQreapXstratXpoc_highLowReap3rdsplit = glm(choice~0 + pastOC1sc*strategyRecode*highReapTopThird +pastOC1sc*strategyRecode*lowReapBottomThird + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode, data=rdmDFclean, family="binomial",offset=predTrialLevModel);
summary(model3);

```



Supplemental analysis results:
```{r temporal-context-effects-replicate}

# Does risk-taking change as a function of past outcome, shift, earnings and expectations? MOVE TO SI ANALYSIS
modelS1 = glm(choice ~ 0 + pastOC1sc + signedShiftsc + earnNormalizedOverall + linExpectation, data=rdmDFclean, family="binomial", offset=predTrialLevModel)
summary(modelS1);

```

```{r additional-shift-analyses}
# In this dataset, we find that signed shift is better behaved than splitting up positive and negative shift:

modelS2a_posNegShift = glm(choice ~ 0 + pastOC1sc + posShiftsc + negShiftsc + earnNormalizedOverall + linExpectation, data=rdmDFclean, family="binomial", offset=predTrialLevModel)
summary(modelS2a_posNegShift); 
# AIC is better (lower) with signed shift.

# In previous datasets, we find that shift effect is short lasting (shift immediately before a trial). Is that the case here? 
modelS2b_howFarBack = glm(choice ~ 0 + pastOC1sc + signedShiftsc + + earnNormalizedOverall + linExpectation + signedShift_1triback, data=rdmDFclean, family="binomial", offset=predTrialLevModel)
summary(modelS2b_howFarBack); 
# Yes, adding shift 1 trial back is not significant.

```

```{r earnings-and-expectations-across-rounds}
# Do people track earnings and expectations across rounds? 
modelS3 =glm(choice ~ 0 + pastOC1sc + signedShiftsc + earnNormalizedOverall+ linExpectation+ earningsAcrossRounds + linExpAcrossRounds, data=rdmDFclean, family="binomial", offset=predTrialLevModel)
summary(modelS3);

# Just include earnings and expectations across rounds (remove earnings and expectations within round)
modelS4 =glm(choice ~ 0 + pastOC1sc + signedShiftsc + earningsAcrossRounds + linExpAcrossRounds, data=rdmDFclean, family="binomial", offset=predTrialLevModel)
summary(modelS4);

```

```{r earnings-expectations-switch-vs-repeat-conditions}
# Do people who switch conditions vs. repeat conditions treat earnings and expectations differently across rounds?

# defining condition codes:
condcode1 = rcsSubLevelWide_clean$subID[rcsSubLevelWide_clean$condCode==1]
condcode2 = rcsSubLevelWide_clean$subID[rcsSubLevelWide_clean$condCode==2]
condcode3 = rcsSubLevelWide_clean$subID[rcsSubLevelWide_clean$condCode==3]
condcode4 = rcsSubLevelWide_clean$subID[rcsSubLevelWide_clean$condCode==4]


# Subset data for those who repeated conditions (condition codes 1 and 4)
repeatconditions = c(condcode1, condcode4)
rdmDFrepeatCond = rdmDFclean[as.numeric(rdmDFclean$subID) %in% repeatconditions,]

# Subset data for those who switched conditions (condition codes 2 and 3)
switchconditions = c(condcode2, condcode3)
rdmDFswitchCond = rdmDFclean[as.numeric(rdmDFclean$subID) %in% switchconditions,]


# Run trial-level models that include round x strategy as we did in model 1 in main analysis:
trialLevel_repeatConditions= glmer(choice ~ 1 + gainScaled + safeScaled + evLevScaled + roundRecode*strategyRecode + (1|subID), data=rdmDFrepeatCond , family = "binomial")
summary(trialLevel_repeatConditions);

trialLevel_swithConditions= glmer(choice ~ 1 + gainScaled + safeScaled + evLevScaled + roundRecode*strategyRecode + (1|subID), data=rdmDFswitchCond , family = "binomial")
summary(trialLevel_swithConditions);

# Trial-level model summaries for switch vs repeat conditions -> strategy increases risk-taking for everyone, but this effect is stronger over time for people who repeat condition. More time with specific strategy = stronger effect of that strategy.


# Save predicted values to the switch and repeat datasets
rdmDFrepeatCond$pred= predict(trialLevel_repeatConditions,type="link"); 
rdmDFswitchCond$pred= predict(trialLevel_swithConditions,type="link"); 

# Do we see the same temporal context effects as above in the whole dataset
# For repeat conditions:
model1_repeatConditions = glm(choice ~ 0 + pastOC1sc + signedShiftsc + linExpectation + earnNormalizedOverall, data=rdmDFrepeatCond, family="binomial", offset=pred);
summary(model1_repeatConditions);
# main effects as above except no effect of signed shift (p = .13) in people who repeat condition

# switch:
model1_switchConditions = glm(choice ~ 0 + pastOC1sc + signedShiftsc + linExpectation + earnNormalizedOverall, data=rdmDFswitchCond, family="binomial", offset=pred);
summary(model1_switchConditions);
# main effects same as above - including effect of signed shift for people who switch conditions



# Could people who switch vs. repeat be treating expectations and earnings differently  (i.e. tracking earnings across rounds)?

# Repeat:
model2_repeatcond_acrossRounds = glm(choice ~ 0 + pastOC1sc + signedShiftsc + linExpAcrossRounds + earningsAcrossRounds, data=rdmDFrepeatCond, family="binomial", offset=pred);
summary(model2_repeatcond_acrossRounds);
#AIC is an improvement from model above with expectations and earnings within round (AIC: 15039) 

# Switch
model2_switchcond_acrossRounds = glm(choice ~ 0 + pastOC1sc + signedShiftsc + linExpAcrossRounds + earningsAcrossRounds, data=rdmDFswitchCond, family="binomial", offset=pred);
summary(model2_switchcond_acrossRounds);
# AIC much worse than model with linear expectations and earnings within round (AIC: 15160)

# Summary -> people who repeat conditions seem to track expectations and earnings across rounds (direction of effects are consistent across groups though) but people who switch appear to treat expectations and earnings separately across rounds.


```

```{r temporal-context-effects-and-strategy}
# Does strategy interact with temporal context?
modelS5= glm(formula = choice ~ 0 + pastOC1sc*strategyRecode + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode, family = "binomial", data = rdmDFclean, offset = predTrialLevModel)
summary(modelS5);

# Does the effect of strategy on context vary with round? 
modelS6 = glm(formula = choice ~ 0 + pastOC1sc*strategyRecode*roundRecode + signedShiftsc*strategyRecode*roundRecode + earnNormalizedOverall*strategyRecode*roundRecode + linExpectation*strategyRecode*roundRecode, family = "binomial", data = rdmDFclean, offset = predTrialLevModel)
summary(modelS6)
```

```{r reaction-time-variability}
# split up trials across rounds into 6 bins (3 in each round)
# bin 1 has 43 trials and 2 & 3 has 44 trials

RTvariability = as.data.frame(matrix(data=NA, nrow=nSub, ncol=6, dimnames = list(c(NULL), c("bin1", "bin2", "bin3", "bin4", "bin5", "bin6"))))

for (s in 1:nSub) {
  subdata = rdmDFclean[rdmDFclean$subID==subIDchar[s],]
  
  RTvariability$bin1[s] = var(subdata$RT[subdata$roundRDM==1 & subdata$trial %in% c(1:43)])
  RTvariability$bin2[s] = var(subdata$RT[subdata$roundRDM==1 & subdata$trial %in% c(44:87)])
  RTvariability$bin3[s] = var(subdata$RT[subdata$roundRDM==1 & subdata$trial %in% c(88:131)])

  RTvariability$bin4[s] = var(subdata$RT[subdata$roundRDM==2 & subdata$trial %in% c(1:43)])
  RTvariability$bin5[s] = var(subdata$RT[subdata$roundRDM==2 & subdata$trial %in% c(44:87)])
  RTvariability$bin6[s] = var(subdata$RT[subdata$roundRDM==2 & subdata$trial %in% c(88:131)])
}


par(mfrow = c(2,3), pty="s")
plot(RTvariability$bin1, ylim=c(0, .85), ylab="RT variability", main="Bin 1: Round 1\nTrials 1-43", xlab="participant", pch=16, lwd=4, col="red", axes=F)
axis(1, at = c(1,62,124), lwd=4)
axis(2, lwd=4)
plot(RTvariability$bin2, ylim=c(0, .85), ylab="RT variability", main="Bin 2: Round 1\nTrials 44-87", xlab="participant", pch=16, lwd=4, col="blue", axes=F)
axis(1, at = c(1,62,124), lwd=4)
axis(2, lwd=4)
plot(RTvariability$bin3, ylim=c(0, .85), ylab="RT variability", main="Bin 3: Round 1\nTrials 88-131", xlab="participant", pch=16, lwd=4, col="green", axes=F)
axis(1, at = c(1,62,124), lwd=4)
axis(2, lwd=4)
plot(RTvariability$bin4, ylim=c(0, .85), ylab="RT variability", main="Bin 4: Round 2\nTrials 1-43", xlab="participant", pch=17, lwd=4, col="red", axes=F)
axis(1, at = c(1,62,124), lwd=4)
axis(2, lwd=4)
plot(RTvariability$bin5, ylim=c(0, .85), ylab="RT variability", main="Bin 5: Round 2\nTrials 44-87", xlab="participant", pch=17, lwd=4, col="blue", axes=F)
axis(1, at = c(1,62,124), lwd=4)
axis(2, lwd=4)
plot(RTvariability$bin6, ylim=c(0, .85), ylab="RT variability", main="Bin 6: Round 2\nTrials 88-131", xlab="participant", pch=17, lwd=4, col="green", axes=F)
axis(1, at = c(1,62,124), lwd=4)
axis(2, lwd=4)


# calculate variability in RT within each bin for each participant. Then take the mean variability across people.

meanRTbins = colMeans(RTvariability)
semRTbins = c(sem(RTvariability$bin1),sem(RTvariability$bin2),sem(RTvariability$bin3),sem(RTvariability$bin4),sem(RTvariability$bin5),sem(RTvariability$bin6))
upperError = meanRTbins + semRTbins
lowerError = meanRTbins - semRTbins


par(mfrow=c(1,1))
plot(meanRTbins, ylim=c(0,.3), main="RT variability across gambling task rounds\n (Error bars: SEM)", xlab="Bins", ylab="mean RT variability", axes=F, pch=c(16,16, 16, 17,17,17), col = c("red", "blue", "green", "red", "blue", "green"), cex=1.5)
arrows(c(1:6),lowerError, c(1:6), upperError, length=0, col = c("red", "blue", "green", "red", "blue", "green"), lwd=3)
axis(1, at = c(1:6), labels = c(1:6), lwd=4)
axis(2, lwd=4)
legend("bottomleft", legend=c("Round 1: trials 1-43", "Round 1: trials 44-87", "Round 1: trials 88-131", "Round 2: trials 1-43", "Round 2: trials 44-87", "Round 2: trials 88-131"),lty=1, lwd=3, bty="n",col = c("red", "blue", "green", "red", "blue", "green"), cex=1, pch=c(16,16, 16, 17,17,17))


```

```{r additional-covariate-models}

# MOTIVATION
# Does motivation interact with strategy to influence risk-taking?
modelS7a_motivationOnly = glm(choice~0+pastOC1sc*strategyRecode + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode + strategyRecode*motivationNumeric, data=rdmDFclean, family="binomial", offset=predTrialLevModel);
summary(modelS7a_motivationOnly);

# ERQ REAPPRAISAL
modelS7b_reappraisalOnly = glm(choice~0+pastOC1sc*strategyRecode + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode + strategyRecode*reapSpan0mean, data=rdmDFclean, family="binomial", offset=predTrialLevModel);
summary(modelS7b_reappraisalOnly);


# ERQ SUPPRESSION
# Does habitual use of expressive suppression interact with strategy to influence risk-taking?
modelS7c_suppressionOnly = glm(choice~0+pastOC1sc*strategyRecode + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode + strategyRecode*suppSpan0mean, data=rdmDFclean, family="binomial", offset=predTrialLevModel);
summary(modelS7c_suppressionOnly);


# COMPOSITE SPAN (WORKING MEMORY CAPACITY)
# Does working memory capacity interact with strategy to influence risk-taking?
modelS7d_compositeSpanOnly = glm(choice~0+pastOC1sc*strategyRecode + signedShiftsc*strategyRecode + earnNormalizedOverall*strategyRecode + linExpectation*strategyRecode + strategyRecode*compositeSpanScore, data=rdmDFclean, family="binomial", offset=predTrialLevModel);
summary(modelS7d_compositeSpanOnly);


```

```{r immediate-global-interaction}
# Interact past outcome with both global timescale variables:
modelS8_POCxEarn_POCxExp = glm(choice ~ 0 + pastOC1sc + signedShiftsc + earnNormalizedOverall*pastOC1sc + linExpectation*pastOC1sc, data=rdmDFclean, family="binomial", offset=predTrialLevModel)
summary(modelS8_POCxEarn_POCxExp); 

```

